/// generated by chatgpt

import 'package:flutter_test/flutter_test.dart';
import 'package:uplift/models/user_model.dart';
import 'package:uplift/models/donor_model.dart';
import 'package:uplift/models/recipient_model.dart';

void main() {
  group('User Model', () {
    test('fromJson parses recipient user correctly', () {
      final json = {
        'id': 1,
        'createdAt': '2025-04-21T12:34:56.000Z',
        'cognitoId': 'abc123',
        'email': 'recipient@example.com',
        'recipient': true,
        'recipientData': {
          'id': 1,
          'firstName': 'Jane',
          'lastName': 'Doe',
          'city': 'Springfield',
          'createdAt': '2025-04-21T12:34:56.000Z',
        },
      };

      final user = User.fromJson(json);

      expect(user.id, 1);
      expect(user.cognitoId, 'abc123');
      expect(user.recipient, true);
      expect(user.recipientData, isNotNull);
      expect(user.donorData, isNull);
    });

    test('fromJson parses donor user correctly', () {
      final json = {
        'id': 2,
        'createdAt': '2025-04-21T12:34:56.000Z',
        'cognitoId': 'xyz789',
        'email': 'donor@example.com',
        'recipient': false,
        'donorData': {
          'id': 1,
          'nickname': 'JohnD',
          'createdAt': '2025-04-21T12:34:56.000Z',
        },
      };

      final user = User.fromJson(json);

      expect(user.id, 2);
      expect(user.cognitoId, 'xyz789');
      expect(user.recipient, false);
      expect(user.recipientData, isNull);
      expect(user.donorData, isNotNull);
    });

    test('toJson outputs expected map', () {
      final user = User(
        id: 3,
        createdAt: DateTime.parse('2025-04-21T12:34:56.000Z'),
        cognitoId: 'testId',
        email: 'test@example.com',
        recipient: false,
        donorData: Donor(id: 1, nickname: 'DonorNick', createdAt: DateTime.parse('2025-04-21T12:34:56.000Z')),
      );

      final json = user.toJson();

      expect(json['id'], 3);
      expect(json['cognitoId'], 'testId');
      expect(json['recipient'], false);
      expect(json['donorData'], isNotNull);
      expect(json['recipientData'], isNull);
    });
  });
}
