name: DBML

on:
  push:
    branches: [ main ]
    paths: [ Design/Database/** ]
  pull_request:
    branches: [ main ]
    paths: [ Design/Database/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Check dbdocs
        run: dbdocs

      - name: Update dbdocs project
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build ./Design/Database/upLiftSchemaDesign.dbml --project cs599-uplift
