# Action that does full CI/CD for Spring Orchestrator, only on push/merge to main
name: Orchestrator CICD

on:
  push:
    branches: [ main ]
    paths: [ Spring Orchestrator/** ]

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Run tests
        run: mvn -Pci -f "./Spring Orchestrator/pom.xml" clean test

  build:
    needs: test
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn -Pprod -f "./Spring Orchestrator" clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"
      - name: Build docker image
        run: docker build -t als5289/uplift-orchestrator "./Spring Orchestrator"
      - name: Push docker image
        run: docker push als5289/uplift-orchestrator:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Check Docker Installation
        run: |
          if ! [ -x "$(command -v docker)" ]; then
            echo "Error: Docker is not installed." >&2
            exit 1
          fi
      - name: Delete all existing containers & images
        run: |
          if [ "$(sudo docker ps -aq)" ]; then
            sudo docker rm -vf $(sudo docker ps -aq)
          fi
          if [ "$(sudo docker images -aq)" ]; then
            sudo docker rmi -f $(sudo docker images -aq)
          fi
      - name: Pull image from docker hub
        run: sudo docker pull als5289/uplift-orchestrator:latest
      - name: Run docker container
        run: sudo docker run -d -p 80:8080 -p 3306:3306 -e TREMENDOUS_API_KEY=${{ secrets.TREMENDOUS_API_KEY }} -e BEDROCK_ACCESS=${{ secrets.BEDROCK_ACCESS }} -e BEDROCK_SECRET=${{ secrets.BEDROCK_SECRET }} --name uplift-orchestrator als5289/uplift-orchestrator 
